# Generated by Django 3.2.7 on 2021-09-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChanged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_title', models.CharField(max_length=20, verbose_name='Название заголовка')),
                ('price_title_desc', models.CharField(max_length=50, verbose_name='Название подзаголовка')),
                ('price_money', models.CharField(max_length=10, verbose_name='Цена')),
                ('price_text_1', models.CharField(max_length=20, verbose_name='Название первого текста')),
                ('price_text_2', models.CharField(max_length=20, verbose_name='Название второго текста')),
                ('price_text_3', models.CharField(max_length=20, verbose_name='Название третьего текста')),
                ('price_text_4', models.CharField(max_length=20, verbose_name='Название четвёртого текста')),
                ('price_text_5', models.CharField(max_length=20, verbose_name='Название пятого текста')),
                ('price_btn', models.CharField(max_length=20, verbose_name='Название кнопки')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='PriceChangedTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_title', models.CharField(max_length=20, verbose_name='Заголовок цен')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Заголовок',
            },
        ),
    ]
