# Generated by Django 3.2.7 on 2021-09-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210924_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='sliderimg/'),
        ),
    ]
