# Generated by Django 3.2.7 on 2021-09-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReloadTitleDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtd_title', models.CharField(max_length=30, verbose_name='заголовки в карточке')),
                ('rtd_desc', models.TextField(max_length=120, verbose_name='Описание карточки')),
                ('rtd_button', models.CharField(max_length=20, verbose_name='Описание кнопки')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
