# Generated by Django 3.2.7 on 2021-09-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_reloadtitledesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reloadtitledesc',
            name='rtd_desc',
            field=models.TextField(max_length=220, verbose_name='Описание карточки'),
        ),
    ]
