# Generated by Django 3.2.7 on 2021-09-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_img', models.ImageField(upload_to='teamimg/')),
                ('team_name', models.CharField(max_length=80, verbose_name='Имя человека')),
                ('team_tag', models.CharField(max_length=20, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Человек',
            },
        ),
        migrations.CreateModel(
            name='TeamMainTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_title', models.CharField(max_length=30, verbose_name='Название заголовка')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Заголовок',
            },
        ),
    ]
