# Generated by Django 3.2.7 on 2021-09-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teambox',
            name='team_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на страницу'),
        ),
    ]
