# Generated by Django 3.2.7 on 2021-09-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildws', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildwebsite',
            name='bw_button',
        ),
    ]
