# Generated by Django 3.2.7 on 2021-09-27 11:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_name', models.CharField(max_length=15, verbose_name='Название модели')),
                ('header_single_letter', models.CharField(max_length=1, verbose_name='Заглавная буква лого')),
                ('header_logo_text', models.CharField(max_length=20, verbose_name='Текст букв лого')),
                ('header_main', models.CharField(max_length=250, verbose_name='Название меню')),
                ('header_features', models.CharField(max_length=250, verbose_name='Название 2 блока')),
                ('header_work', models.CharField(max_length=250, verbose_name='Название 3 блока')),
                ('header_service', models.CharField(max_length=250, verbose_name='Название 4 блока')),
                ('header_blog', models.CharField(max_length=250, verbose_name='Название 5 блока')),
                ('header_price', models.CharField(max_length=250, verbose_name='Название 6 блока')),
                ('header_about', models.CharField(max_length=250, verbose_name='Название 7 блока')),
                ('header_contact', models.CharField(max_length=250, verbose_name='Название 7 блока')),
                ('header_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
            options={
                'verbose_name': 'HEADER',
                'verbose_name_plural': 'HEADER',
            },
        ),
    ]
