# Generated by Django 3.2.7 on 2021-09-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_logo_img', models.ImageField(upload_to='footerimg/')),
                ('footer_title', models.TextField()),
                ('footer_facebook', models.CharField(max_length=250, verbose_name='Ссылка на фейсбук')),
                ('footer_twitter', models.CharField(max_length=250, verbose_name='Ссылка на твиттер')),
                ('footer_in', models.CharField(max_length=250, verbose_name='Ссылка на in')),
                ('footer_telegram', models.CharField(max_length=250, verbose_name='Ссылка на telegram')),
                ('footer_vimeo', models.CharField(max_length=250, verbose_name='Ссылка на vimeo')),
                ('footer_pictures', models.CharField(max_length=250, verbose_name='Ссылка на pictures')),
                ('footer_left_title', models.CharField(max_length=250, verbose_name='Заголовок (слева) контакт')),
                ('footer_left_map', models.CharField(max_length=250, verbose_name='Контакт Адрес')),
                ('footer_left_email', models.CharField(max_length=250, verbose_name='Контакт почты')),
                ('footer_center_title', models.CharField(max_length=250, verbose_name='Заголовок center')),
                ('footer_center_desc', models.CharField(max_length=250, verbose_name='Описание работы')),
                ('footer_center_work', models.CharField(max_length=250, verbose_name='MON - FRI : 9.00 AM TO 5.00 PM')),
                ('footer_center_work1', models.CharField(max_length=250, verbose_name='SAT - SUN : 11.00 AM TO 3.00 PM')),
                ('footer_right_title', models.CharField(max_length=250, verbose_name='Заголовок справа')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.AlterModelOptions(
            name='changeheader',
            options={'verbose_name': 'Header', 'verbose_name_plural': 'Header'},
        ),
    ]
