# Generated by Django 3.2.7 on 2021-09-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloges', '0002_auto_20210928_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeFooterGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_right_title', models.CharField(max_length=250, verbose_name='Заголовок справа')),
                ('footer_right_img', models.ImageField(upload_to='footerimg/')),
            ],
            options={
                'verbose_name': 'Footer gallery',
                'verbose_name_plural': 'Footer gallery',
            },
        ),
        migrations.RemoveField(
            model_name='changefooter',
            name='footer_right_title',
        ),
    ]
