# Generated by Django 3.2.7 on 2021-09-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloges', '0004_alter_changefootergallery_footer_right_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeFooterTitleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_right_title', models.CharField(max_length=250, verbose_name='Заголовок справа')),
            ],
            options={
                'verbose_name': 'Footer gallery',
                'verbose_name_plural': 'Footer gallery',
            },
        ),
        migrations.AlterModelOptions(
            name='changefootergallery',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.RemoveField(
            model_name='changefootergallery',
            name='footer_right_title',
        ),
        migrations.AddField(
            model_name='changefootergallery',
            name='footer_right_name',
            field=models.CharField(default='this stroke', max_length=250, verbose_name='Название картинки'),
        ),
    ]
