# Generated by Django 3.2.7 on 2021-09-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloges', '0005_auto_20210928_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changefootertitlegallery',
            options={'verbose_name': 'Заголовок справа', 'verbose_name_plural': 'Заголовок справа'},
        ),
    ]
