# Generated by Django 3.2.7 on 2021-09-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmblog',
            name='fm_img',
            field=models.ImageField(blank=True, null=True, upload_to='fmblogimg/'),
        ),
    ]
