# Generated by Django 3.2.7 on 2021-09-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0003_fmblog_post_btn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmblog',
            name='status',
            field=models.CharField(choices=[('close', 'Close'), ('published', 'Published')], default='published', max_length=15),
        ),
    ]
