# Generated by Django 3.2.7 on 2021-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0004_alter_fmblog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_title', models.CharField(max_length=20, verbose_name='Заголовок блога')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Заголовки',
            },
        ),
    ]
