# Generated by Django 3.2.7 on 2021-09-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0006_postcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='fmblog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fmblog.fmblog'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
