# Generated by Django 3.2.7 on 2021-09-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0007_auto_20210930_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='category_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название Заголовка'),
        ),
    ]
