# Generated by Django 3.2.7 on 2021-09-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0008_postcategory_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeTitleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=250, verbose_name='Название Заголовка')),
            ],
            options={
                'verbose_name': 'Заголовок категорий',
                'verbose_name_plural': 'Заголовок категорий',
            },
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='category_title',
        ),
    ]
