# Generated by Django 3.2.7 on 2021-09-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0009_auto_20210930_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название чего'),
        ),
    ]
