# Generated by Django 3.2.7 on 2021-09-30 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0011_auto_20211001_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmblog',
            name='categorylist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fmblog.categorylist'),
        ),
    ]
