# Generated by Django 3.2.7 on 2021-09-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0012_alter_fmblog_categorylist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fmblog',
            old_name='categorylist',
            new_name='category_list',
        ),
    ]
