# Generated by Django 3.2.7 on 2021-09-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0013_rename_categorylist_fmblog_category_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylist',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
