# Generated by Django 3.2.7 on 2021-10-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0015_rename_category_list_fmblog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmblog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fmblog.categorylist'),
        ),
    ]
