# Generated by Django 3.2.7 on 2021-10-10 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0016_alter_fmblog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylist',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fmblog.categorylist'),
        ),
    ]
