# Generated by Django 3.2.7 on 2021-10-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0017_categorylist_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylist',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fmblog.categorylist'),
        ),
    ]
