# Generated by Django 3.2.7 on 2021-10-11 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0018_alter_categorylist_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmblog',
            name='category',
        ),
        migrations.AlterField(
            model_name='categorylist',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fmblog.fmblog'),
        ),
    ]
