# Generated by Django 3.2.7 on 2021-10-11 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0020_auto_20211011_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmblog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fmblog.categorylist'),
        ),
    ]
