# Generated by Django 3.2.7 on 2021-10-23 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0023_fmblog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylist',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fmblog.fmblog'),
        ),
    ]
