# Generated by Django 3.2.7 on 2021-10-24 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmblog', '0024_alter_categorylist_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylist',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fmblog.fmblog'),
        ),
    ]
