# Generated by Django 3.2.7 on 2021-09-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(upload_to='sliderimg/')),
                ('slider_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slider_css', models.CharField(default='-', max_length=200, null=True, verbose_name='css class')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
