# Generated by Django 3.2.7 on 2021-09-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_features_fts_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='fts_img',
            field=models.ImageField(blank=True, upload_to='sliderimg/'),
        ),
    ]
