# Generated by Django 3.2.7 on 2021-09-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_alter_features_fts_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='fts_desc',
            field=models.TextField(max_length=120, verbose_name='Описание'),
        ),
    ]
